services:
  cache:
    image: redis:6
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  directus:
    image: directus/directus:11.1.0
    ports:
      - 8055:8055
    volumes:
      - directus-uploads:/directus/uploads
      - directus-extensions:/directus/extensions
      - directus-db:/directus/database
    depends_on:
      cache:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SECRET: ${SECRET}

      DB_CLIENT: sqlite3
      DB_FILENAME: /directus/database/directus.db

      CACHE_ENABLED: true
      CACHE_AUTO_PURGE: true
      CACHE_STORE: redis
      REDIS: redis://cache:6379

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

volumes:
  directus-uploads:
  directus-extensions:
  directus-db:
