services:
  database:
    image: mariadb:lts-ubi9
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: directus
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always

  cache:
    image: redis:6
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
    restart: always

  directus:
    image: directus/directus:11.1.0
    ports:
      - 8055:8055
    volumes:
      - directus-uploads:/directus/uploads
      - directus-extensions:/directus/extensions
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SECRET: ${SECRET}

      DB_CLIENT: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: directus
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      CACHE_ENABLED: true
      CACHE_AUTO_PURGE: true
      CACHE_STORE: redis
      REDIS: redis://cache:6379

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    restart: always

volumes:
  directus-uploads:
  directus-extensions:
  mariadb-data: